---aaabbb
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhoujie.
--- DateTime: 2022/9/30 16:57
---
lib996:include("Script/A/NPC点击.lua")


lib996:include("Script/A/一键满血.lua")
lib996:include("Script/A/沙城捐献.lua")
lib996:include("Script/A/狂暴之力.lua")
lib996:include("Script/A/转生之力.lua")
lib996:include("Script/A/称号升级.lua")
lib996:include("Script/A/免费会员.lua")


lib996:include("Script/A/测试1.lua")
