---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 19838.
--- DateTime: 2022/10/11 12:48
---


lib996:include("Script/serialize.lua")

function npcclick(actor, npcid)
    --一键满血
    if npcid == 1 then
        yijianmanxue(actor)
    --    狂暴之力
    elseif npcid == 2 then
        kuangbaozhili(actor)
    --    沙城捐献
    elseif npcid == 3 then
        shachengjuanxian(actor)
    --    转生
    elseif npcid == 4 then
        zhuanshengzhili(actor)
    --    称号
    elseif npcid == 5 then
        chenghaoshengji(actor)
    --    强化
    elseif npcid == 6 then
    elseif npcid == 7 then

    elseif npcid == 8 then
    elseif npcid == 10 then
        mianfeihuiyuan(actor)
    elseif npcid == 11 then
        lib996:map(actor, "BX3")
    elseif npcid == 18 then
        ceshi1(actor)
    end
end

GameEvent.add(EventCfg.onClicknpc, npcclick, "点击npc")