---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhoujie.
--- DateTime: 2022/9/30 16:58
---

lib996:include("Script/serialize.lua")

function ceshi1(actor)
    --lib996:newpicktask(actor,1,'任务状态','当前杀怪数量')
    --lib996:newcompletetask(actor,1)
    local str = string.gsub("<font color='#efeded'>击杀</font>" .. "<font color='#ff7f50'>50级</font>" .. "<font color='white'>以上怪物</font>" .. "<font color='#ef321b'>杀怪数量/10</font>", "杀怪数量", 5)

    lib996:newchangetask(actor,1,str)
end

--GameEvent.add(EventCfg.onClicknpc, ceshi1, "测试1")