---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhoujie.
--- DateTime: 2022/9/30 16:58
---

lib996:include("Script/serialize.lua")

function ceshi1(actor)
    ----lib996:setint(0, actor, "个人捐献数量",10)
    ----lib996:setsysint("捐献总数", 10);
    ----print(lib996:getsysint("捐献总数").."---------------")
    --lib996:playeffect(actor, 30119,0,0,0,0,0)
    --if lib996:checktitle(actor, "第二富豪") then
    --    print("---------------------11111")
    --end
    --lib996:superman(actor,1)
    --lib996:confertitle(actor, "狂暴之力")
    --local tbl = {
    --    [1] = {
    --        [1] = ConstCfg.money.ddqg,
    --        [2] = 100000,
    --    },
    --    [2] = {
    --        [1] = ConstCfg.money.beigong,
    --        [2] = 1000
    --    }
    --}
    --lib996:playeffect(actor, 30117,0,0,0,0,0)

    --lib996:confertitle(actor, "初入江湖")
    --openUI(actor)
    --local c = lib996:getitemattr(actor, makeid, -1)
    --print(c)

    --local item = lib996:linkbodyitem(actor, 1)
    --local makeid = lib996:getiteminfo(actor, item, 1)
    --local itemobject = lib996:getitembymakeindex(actor,makeid)
    --if item == itemobject then
    --    print("==")
    --else
    --    print("~=")
    --end
    --local item = lib996:linkbodyitem(actor, 1)
    --local makeid = lib996:getiteminfo(actor, item, 1)
    --lib996:additemattr(actor, makeid, 30, 1, 100)
    --lib996:changeitemupgradecount(actor, 0, 10)
    --RequestOpenWnd(actor)
    --lib996:setint(0, actor, "当前会员等级", 5)
    --FBackZone(actor)
end

--GameEvent.add(EventCfg.onClicknpc, ceshi1, "测试1")