---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 19838.
--- DateTime: 2022/10/15 13:09
---

lib996:include("Script/serialize.lua")
local cfg = {
    name = "狂暴之力",
    cost = {
        [1] = ConstCfg.money.rmb,
        [2] = 100,
    },
    shuxing = {
        [1] = {
            [1] = 1,
            [2] = 1000,
        },
    },
    money = {
        [1] = {
            [1] = ConstCfg.money.beigong,
            [2] = 100,
        },
        [2] = {
            [1] = ConstCfg.money.baolv,
            [2] = 100,
        },
        [3] = {
            [1] = ConstCfg.money.ddqg,
            [2] = 100000,
        }
    },
    effectid = 30111,
    diaoluo = {
        [1] = ConstCfg.money.rmb,
        [2] = 50,
    },
    msg = {
        yikaiqi = '{"Msg":"<font color=\'#ff0000\'>请勿重复开启狂暴！</font>","Type":9}',
        rmbbuzu = '{"Msg":"<font color=\'#ff0000\'>RMB点不足！</font>","Type":9}',
        kaiqichenggong = '{"Msg":"<font color=\'#ff0000\'>开启狂暴成功！</font>","Type":9}',
        beishatishi = '{"Msg":"<font color=\'#ff0000\'>狂暴消失！</font>","Type":9}',
        sharenjiangli = '{"Msg":"<font color=\'#ff0000\'>杀死狂暴，奖励50RMB点！</font>","Type":9}',
    },
}

function getcfg_kuangbaozhili()
    return cfg
end

function kuangbaozhili(actor)
    lib996:showformwithcontent(actor, "A/狂暴之力", "")
end

function kuangbao(actor)
    --已开启狂暴
    if lib996:checktitle(actor, cfg.name) then
        lib996:sendmsg(actor, 1, cfg.msg.yikaiqi)
        return
    end
    --检查钱够不够
    if not QsQcheckMoneyNum(actor, cfg.cost[1], cfg.cost[2]) then
        lib996:sendmsg(actor, 1, cfg.msg.rmbbuzu)
        return
    end
    --    开启狂暴
    --    1.扣钱
    lib996:changemoney(actor, cfg.cost[1], "-", cfg.cost[2], "", true)
    --    2.给称号
    lib996:confertitle(actor, cfg.name)
    --    3.给特效
    lib996:playeffect(actor, cfg.effectid, 0, 0, 0, 0)
    --    4.刷新属性
    QsQupdateSomeAddr(actor, {}, cfg.shuxing)
    QsQupdateSomeMoney(actor, {}, cfg.money)
    lib996:sendmsg(actor, 1, cfg.msg.kaiqichenggong)
end

GameEvent.add(EventCfg.onLoginAttr, function(actor, loginattrs)
    if lib996:checktitle(actor, cfg.name) then
        table.insert(loginattrs, cfg.shuxing)
        lib996:playeffect(actor, cfg.effectid, 0, 0, 0, 0, 0)
    end
end, "狂暴之力")

--击杀狂暴
GameEvent.add(EventCfg.onkillplay, function(actor, play)
    --检查被杀的人有没有狂暴
    if not lib996:checktitle(play, cfg.name) then
        return
    end
    --    取消被杀狂暴，杀人的人奖励
    --    1.去掉称号
    lib996:deprivetitle(play, cfg.name)
    --    2.去掉特效
    lib996:clearplayeffect(play, cfg.effectid)
    --3.更新属性
    QsQupdateSomeAddr(play, cfg.shuxing, {})
    QsQupdateSomeMoney(play, cfg.money, {})
    --    4.提示
    lib996:sendmsg(play, 1, cfg.msg.beishatishi)
    --    5.奖励
    lib996:changemoney(actor, cfg.diaoluo[1], "+", cfg.diaoluo[2], "", true)
    --    6.提示
    lib996:sendmsg(actor, 1, cfg.msg.sharenjiangli)
end)