---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhoujie.
--- DateTime: 2022/9/30 16:58
---

lib996:include("Script/serialize.lua")

function ceshi1(actor, npcid)
    if npcid ~= 18 then
        return
    end
    qianghua(actor)
end

GameEvent.add(EventCfg.onClicknpc, ceshi1, "≤‚ ‘1")